### ISSUE TITLE
Incorrect specification of 'all' partners for ct_get_data()

### ISSUE THREAD

**Issue by nealhaddaway** [milos-agathon/trade-routes#1]
The following code specifies 'all' country partners incorrectly:

`wheat_exports <- comtradr::ct_get_data(
  commodity_code = "1001",
  flow_direction = "export",
  reporter = "UKR",
  partner = "all",
  start_date = 2022,
  end_date = 2022
)`

It should be:

`wheat_exports <- comtradr::ct_get_data(
  commodity_code = "1001",
  flow_direction = "export",
  reporter = "UKR",
  partner = "all_countries",
  start_date = 2022,
  end_date = 2022
)`

**Comment by milos-agathon** [comment]
Thanks for bringing this to my attention. just fixed the typo.  Let me know if you find more issues.
